### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by Bencici** [RolfBly/DS1621#1]
Hi,

when I start ds1621.py I get the error:

"ImportTraceback (most recent call last):
  File "/home/pi/capt/ds1621.py", line 37, in <module>
    import datalog
ImportError: No module named datalog"

but I have datalog installed, any idea ?

Thanks in advance.

**Comment by RolfBly** [comment]
datalog.py should be in the same directory as ds1621.py.  

Note that datalog is only called in line 286 to 291, which are commented out. You could just comment out line 37 as well.

**Comment by Bencici** [comment]
Well...I have changed everythings according to your documentation (512Mb version) and it works !

Thanks alot !
